// src/router/buildRoutesFromMenu.ts

import { type RouteObject } from "react-router";
import routeMap, {
  internalRouteMap,
  type RouteConfig,
  type ModuleAction,
} from "./routeMap";

import type { MenuItem } from "@/domains/authentification/schema/navigationSchema";

/* =========================================================
 * TYPES
 * ======================================================= */

interface ModuleNode {
  id: number;
  nom: string;
  menu: MenuItem[];
}

/* =========================================================
 * PERMISSIONS
 * ======================================================= */

/**
 * Vérifie que le menu possède l'action demandée.
 *
 * Exemple :
 *
 * actions: ["view", "create", "edit"]
 *
 * hasAction(item, "view")   => true
 * hasAction(item, "delete") => false
 */
function hasAction(item: MenuItem, action: ModuleAction): boolean {
  return item.actions?.includes(action) ?? false;
}

/**
 * Une route principale est accessible si l'item possède "view".
 */
function hasView(item: MenuItem): boolean {
  return hasAction(item, "view");
}

/* =========================================================
 * INTERNAL ROUTES
 * ======================================================= */

/**
 * Construit les routes internes associées à une route/menu.
 *
 * Exemple :
 *
 * /atelier/demande-intervention
 *
 * peut automatiquement recevoir :
 *
 * /atelier/demande-intervention/dit-list
 * /atelier/demande-intervention/new
 * /atelier/demande-intervention/details/:numeroDemandeIntervention
 * /atelier/demande-intervention/duplication/:numeroDemandeIntervention
 *
 * selon les actions présentes dans item.actions.
 */
function findInternalConfigs(itemRoute: string) {
  if (internalRouteMap[itemRoute]) {
    return { parentKey: itemRoute, configs: internalRouteMap[itemRoute] };
  }
  for (const key of Object.keys(internalRouteMap)) {
    if (itemRoute === key || itemRoute.startsWith(key + "/") || key.startsWith(itemRoute)) {
      return { parentKey: key, configs: internalRouteMap[key] };
    }
  }
  return null;
}

function buildInternalRoutes(
  parentRoute: string,
  item: MenuItem,
  processedPaths: Set<string>,
): RouteObject[] {
  const match = findInternalConfigs(parentRoute);
  if (!match) return [];

  const { parentKey, configs } = match;
  const routes: RouteObject[] = [];

  for (const config of configs) {
    if (config.action && !hasAction(item, config.action)) {
      continue;
    }

    const fullPath = config.path ? `${parentKey}/${config.path}` : parentKey;
    processedPaths.add(fullPath);

    routes.push({
      ...(config.index ? { index: true } : { path: config.path }),
      element: <config.component />,

      ...(config.loader
        ? {
            loader: config.loader,
          }
        : {}),

      handle: {
        title: config.title,
        actions: item.actions,
        scope: item.scope,
        hideFromMenu: true,
        parentRoute,
      },
    });
  }

  return routes;
}

/* =========================================================
 * MAIN ROUTE
 * ======================================================= */

function processMenuItem(
  item: MenuItem,
  processedPaths: Set<string>,
): RouteObject[] {
  const routes: RouteObject[] = [];

  if (item.route && hasView(item)) {
    const config: RouteConfig = routeMap[item.route];

    if (config) {
      const Component = config.component;
      const internalRoutes = buildInternalRoutes(item.route, item, processedPaths);
      processedPaths.add(item.route);

      routes.push({
        path: item.route,
        element: <Component />,
        ...(config.loader ? { loader: config.loader } : {}),

        handle: {
          title: item.nom,
          actions: item.actions,
          scope: item.scope,
        },

        ...(internalRoutes.length > 0
          ? {
              children: internalRoutes,
            }
          : {}),
      });
    } else {
      console.warn(`[Routing] No component mapped for route: ${item.route}`);
    }
  }

  if (item["sous-menu"]?.length) {
    for (const child of item["sous-menu"]) {
      routes.push(...processMenuItem(child, processedPaths));
    }
  }

  return routes;
}

/* =========================================================
 * PUBLIC API
 * ======================================================= */

export function buildRoutesFromMenu(modules: ModuleNode[]): RouteObject[] {
  const routes: RouteObject[] = [];
  const processedPaths = new Set<string>();

  // 1️⃣ Add routes from backend menu
  for (const module of modules) {
    for (const item of module.menu) {
      routes.push(...processMenuItem(item, processedPaths));
    }
  }

  // 2️⃣ Fallback: Register any routeMap entries not generated by menu
  for (const [routePath, routeConfig] of Object.entries(routeMap)) {
    if (!processedPaths.has(routePath)) {
      const Component = routeConfig.component;
      routes.push({
        path: routePath,
        element: <Component />,
        ...(routeConfig.loader ? { loader: routeConfig.loader } : {}),
      });
      processedPaths.add(routePath);
    }
  }

  return routes;
}

export default buildRoutesFromMenu;
