FROM node:20-alpine

WORKDIR /app

# Installation des outils de base pour le debug réseau
RUN apk add --no-cache bash curl

# On ne fait plus npm install ici pour éviter le blocage au build
COPY package*.json ./

EXPOSE 5173

# On lance l'installation au démarrage du conteneur
CMD ["sh", "-c", "npm install && npm run dev -- --host"]
