FROM node:20-alpine

WORKDIR /app

# Installation des outils de base pour le debug réseau
RUN apk add --no-cache bash curl

# Copier et installer les dépendances PENDANT le build
COPY package*.json ./
RUN npm install && npm cache clean --force

# Copier le reste du code
COPY . .

EXPOSE 5173

# Démarrer directement sans npm install
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
