FROM php:8.3-apache-bookworm

ENV INFORMIXDIR=/opt/IBM/Informix_Client-SDK
ENV PATH=$INFORMIXDIR/bin:$PATH
ENV LD_LIBRARY_PATH=$INFORMIXDIR/lib:$INFORMIXDIR/lib/cli:$LD_LIBRARY_PATH
ENV INFORMIXSERVER=ol_informix

RUN apt-get update && apt-get install -y \
    unixodbc unixodbc-dev \
    default-jre \
    libncurses5 \
    wget curl git tar make gcc g++ \
    zip unzip \ 
    && rm -rf /var/lib/apt/lists/*

# === Installation Informix CSDK avec response file ===
WORKDIR /tmp
COPY ibm.csdk.15.0.1.0.Linux.64.x86_64.tar csdk.tar
COPY response.properties response.properties

RUN tar -xvf csdk.tar \
    && tar -xvf ibm.csdk.15.0.1.0.Linux.64.x86_64.tar \
    && chmod +x installclientsdk \
    && ./installclientsdk -i silent -f /tmp/response.properties \
    && echo "=== CSDK installé ===" \
    && ls -la $INFORMIXDIR/bin || echo "Dossier INFORMIXDIR non trouvé"

# === Installation PDO_INFORMIX ===
RUN wget -q https://pecl.php.net/get/PDO_INFORMIX-1.3.7.tgz -O pdo_informix.tgz \
    && tar -xzf pdo_informix.tgz \
    && cd PDO_INFORMIX-1.3.7 \
    && phpize \
    && ./configure --with-pdo-informix=$INFORMIXDIR \
    && make -j2 && make install \
    && echo "extension=pdo_informix.so" > /usr/local/etc/php/conf.d/30-pdo_informix.ini \
    && cd /tmp && rm -rf PDO_INFORMIX* *.tgz

# Variables permanentes pour PHP + Apache
RUN echo "export INFORMIXDIR=/opt/IBM/Informix_Client-SDK" >> /etc/apache2/envvars \
    && echo "export INFORMIXSERVER=ol_iriumprod_net" >> /etc/apache2/envvars \
    && echo "export LD_LIBRARY_PATH=/opt/IBM/Informix_Client-SDK/lib:/opt/IBM/Informix_Client-SDK/lib/cli:/opt/IBM/Informix_Client-SDK/lib/esql:\$LD_LIBRARY_PATH" >> /etc/apache2/envvars

# Pour PHP-CLI aussi
RUN echo "INFORMIXDIR=/opt/IBM/Informix_Client-SDK" > /usr/local/etc/php/conf.d/98-informix-env.ini \
    && echo "LD_LIBRARY_PATH=/opt/IBM/Informix_Client-SDK/lib:/opt/IBM/Informix_Client-SDK/lib/cli:/opt/IBM/Informix_Client-SDK/lib/esql" >> /usr/local/etc/php/conf.d/98-informix-env.ini

# Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Symfony CLI (optionnel mais pratique)
RUN curl -sS https://get.symfony.com/cli/installer | bash \
    && mv /root/.symfony*/bin/symfony /usr/local/bin/symfony

WORKDIR /var/www/html
EXPOSE 80