FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache bash curl

COPY package*.json ./

EXPOSE 3000

# Docusaurus utilise par défaut 'npm start' pour le dev sur le port 3000
CMD ["sh", "-c", "npm install && npm start -- --host 0.0.0.0"]
