framework:
    cache:
        # Redis : adapté pour les données de recherche Informix (TTL court)
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            # Pool dédié à la recherche de matériels (TTL 5 min)
            cache.materiel_search:
                adapter: cache.adapter.redis
                default_lifetime: 300   # 5 minutes
                provider: '%env(REDIS_URL)%'
