doctrine:
    dbal:
        default_connection: ips
        connections:
            ips:
                driver_class: App\Doctrine\Informix\InformixDriver
                host: '%env(INFORMIX_HOST)%'
                port: '%env(INFORMIX_PORT)%'
                dbname: '%env(INFORMIX_DB)%'
                user: '%env(INFORMIX_USER)%'
                password: '%env(INFORMIX_PASSWORD)%'
                server: '%env(INFORMIXSERVER)%'
                protocol: onsoctcp
            irium:
                driver_class: App\Doctrine\Informix\InformixDriver
                host: '%env(INFORMIX_HOST)%'
                port: '%env(INFORMIX_PORT)%'
                dbname: '%env(INFORMIX_DB_IRIUM)%'
                user: '%env(INFORMIX_USER)%'
                password: '%env(INFORMIX_PASSWORD)%'
                server: '%env(INFORMIXSERVER)%'
                protocol: onsoctcp
            sqlserver:
                driver: pdo_sqlsrv
                host: '%env(SQLSERVER_HOST)%'
                port: '%env(SQLSERVER_PORT)%'
                dbname: '%env(SQLSERVER_DB)%'
                user: '%env(SQLSERVER_USER)%'
                password: '%env(SQLSERVER_PASSWORD)%'
                options:
                    TrustServerCertificate: true
    orm:
        default_entity_manager: ips
        entity_managers:
            ips:
                connection: ips
                mappings:
                    ApproIps:
                        type: attribute
                        dir: '%kernel.project_dir%/src/Appro/Entity/Ips'
                        prefix: 'App\Appro\Entity\Ips'
                    ITIps:
                        type: attribute
                        dir: '%kernel.project_dir%/src/IT/Entity/Ips'
                        prefix: 'App\IT\Entity\Ips'
            irium:
                connection: irium
                mappings:
                    ApproIrium:
                        type: attribute
                        dir: '%kernel.project_dir%/src/Appro/Entity/Irium'
                        prefix: 'App\Appro\Entity\Irium'
                    ComptaIrium:
                        type: attribute
                        dir: '%kernel.project_dir%/src/Compta/Entity/Irium'
                        prefix: 'App\Compta\Entity\Irium'
when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
