doctrine:
    dbal:
        default_connection: ips
        connections:
            ips:
                driver_class: App\Doctrine\Informix\InformixDriver
                host: '%env(INFORMIX_HOST)%'
                port: '%env(INFORMIX_PORT)%'
                dbname: '%env(INFORMIX_DB)%'
                user: '%env(INFORMIX_USER)%'
                password: '%env(INFORMIX_PASSWORD)%'
                server: '%env(INFORMIXSERVER)%'
                protocol: onsoctcp
            irium:
                driver_class: App\Doctrine\Informix\InformixDriver
                host: '%env(INFORMIX_HOST)%'
                port: '%env(INFORMIX_PORT)%'
                dbname: '%env(INFORMIX_DB_IRIUM)%'
                user: '%env(INFORMIX_USER)%'
                password: '%env(INFORMIX_PASSWORD)%'
                server: '%env(INFORMIXSERVER)%'
                protocol: onsoctcp
            sqlserver:
                driver_class: App\Doctrine\SqlServer\SqlServerDriver
                host: '%env(SQLSERVER_HOST)%'
                port: '%env(SQLSERVER_PORT)%'
                dbname: '%env(SQLSERVER_DB)%'
                user: '%env(SQLSERVER_USER)%'
                password: '%env(SQLSERVER_PASSWORD)%'
    orm:
        default_entity_manager: ips
        entity_managers:
            ips:
                connection: ips
                mappings:
                    MagasinDevisIps:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Magasin/Devis/Entity/Ips'
                        prefix: 'App\Magasin\Devis\Entity\Ips'
                    DitIps:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Dit/Entity/Ips'
                        prefix: 'App\Dit\Entity\Ips'
                filters:
                    user_scope:
                        class: App\Security\Doctrine\UserScopeFilter
                        enabled: false
            irium:
                connection: irium
                mappings:
                    MagasinDevisIrium:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Magasin/Devis/Entity/Irium'
                        prefix: 'App\Magasin\Devis\Entity\Irium'
                    DitIrium:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Dit/Entity/Irium'
                        prefix: 'App\Dit\Entity\Irium'
            sqlserver:
                connection: sqlserver
                mappings:
                    Security:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Security/Entity'
                        prefix: 'App\Security\Entity'
                    Audit:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Audit/Entity'
                        prefix: 'App\Audit\Entity'
                    Notification:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Notification/Entity'
                        prefix: 'App\Notification\Entity'
                    Tik:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Tik/Entity'
                        prefix: 'App\Tik\Entity'
                    Dit:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Dit/Entity/SqlServer'
                        prefix: 'App\Dit\Entity\SqlServer'
when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
