nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api(?!/doc$)
    documentation:
        info:
            title: HFF Intranet API
            description: Documentation interactive du backend Symfony 7 (LDAP + JWT + ACL)
            version: 1.0.0
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - bearerAuth: []
