security:

    password_hashers:
        App\Security\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Security\Entity\User
                property: username
                manager_name: sqlserver

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            stateless: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\LdapAuthenticator
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
