import type { Dit } from "./ditSchema";

export const ditMock: Dit[] = [
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "PARC 701",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    detailDemande: "Voici les details de la demande ",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "PARC 701",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    detailDemande: "Voici les details de la demande ",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "PARC 701",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    detailDemande: "Voici les details de la demande ",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    detailDemande: "Voici les details de la demande ",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    detailDemande: "Voici les details de la demande ",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    detailDemande: "Voici les details de la demande ",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    detailDemande: "Voici les details de la demande ",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    detailDemande: "Voici les details de la demande ",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    detailDemande: "Voici les details de la demande ",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    detailDemande: "Voici les details de la demande ",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    detailDemande: "Voici les details de la demande ",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    detailDemande: "Voici les details de la demande ",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    detailDemande: "Voici les details de la demande ",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    detailDemande: "Voici les details de la demande ",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    detailDemande: "Voici les details de la demande ",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
  {
    id: 1,
    idStatutDemande: 1,
    statutDemande: "A AFFECTER",
    numeroDemandeIntervention: "DIT26068682",
    reparationRealise: "ATE TANA",
    typeDocument: "Maintenance préventive",
    worNiveauUrgence: "P2",
    categorieDemande: "REPARATION",
    numSerie: "7W802986",
    numParc: "Couleur :",
    dateDemande: "2026-06-22",
    interneExterne: "EXTERNE",
    agenceEmetteur: "01-ATE",
    agenceDebiteur: "01-ATE",
    serviceEmmeteur: "01-ATE",
    serviceDebiteur: "01-ATE",
    objetDemande: "RECONDITION TC WITHOUT HOUSING 777E - ITEM 1542 (FLAT RATE)",
    sectionAffectee: "Section TVm",
    numeroDevisRattache: "1234568",
    statutDevis: "En cours de validation",
    numeroOr: "21312293",
    statutOr: "Validé",
    montantOr: 1000000,
    dateSoumissionOr: "2026-06-22",
    etatFacturation: "Payée",
    ri: "1/10",
    nbrPj: 0,
    utilisateurDemandeur: "HOLY",
    estAnnulable: true,
    estOrASoumi: false,
    quantiteDemanderOr: 0,
    quantiteReserverOr: 0,
    quantiteLivreeOr: 0,
    quantiteReliquatOr: 0,
    qteLivOr: 0,
    etatLivraison: "Non livré",
    detailDemande: "Voici les details de la demande ",
  },
];
